name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the solution
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you want!
    validations:
      required: true
