name: Edit request
description: Request for edits of the Atlas data 
labels: ["entry update"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the changes
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you want!
    validations:
      required: true