name: Qodana
on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - master
    paths:
      - "**.js"
      - "**.sh"
      - "**.py"
  push:
    branches:
      - master
    paths:
      - "**.js"
      - "**.sh"
      - "**.py"

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check using Qodana
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          
