name: Validate JSON
on:
  push:
    paths:
      - web/atlas.json
  pull_request:
    paths:
      - web/atlas.json
jobs:
  Validate-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Validate JSON
        run: python3 tools/ci/validate_json.py web/atlas.json